<?php

return [
    'supported' => [
        'EUR' => '€',
        'USD' => '$',
        'GBP' => '£',
        'BGN' => 'лв.',
        'CHF' => 'CHF',
        'JPY' => '¥',
        'CNY' => '¥',
        'AUD' => '$',
        'CAD' => '$',
        'NZD' => '$',
        'SEK' => 'kr',
        'NOK' => 'kr',
        'DKK' => 'kr',
        'PLN' => 'zł',
        'CZK' => 'Kč',
        'HUF' => 'Ft',
        'RON' => 'lei',
        'TRY' => '₺',
        'UAH' => '₴',
        'RSD' => 'дин.',
        'RUB' => '₽',
        'INR' => '₹',
        'KRW' => '₩',
        'SGD' => '$',
        'HKD' => '$',
        'BRL' => 'R$',
        'MXN' => '$',
        'ZAR' => 'R',
        'ILS' => '₪',
        'AED' => 'د.إ',
        'SAR' => 'ر.س',
        'QAR' => 'ر.ق',
        'KWD' => 'د.ك',
        'BHD' => '.د.ب',
        'EGP' => '£',
        'THB' => '฿',
        'IDR' => 'Rp',
        'MYR' => 'RM',
        'PHP' => '₱',
        'VND' => '₫',
        'NGN' => '₦',
        'KES' => 'KSh',
        'GHS' => '₵',
    ],
];
